### ISSUE TITLE
Debugging requires user input to start

### ISSUE THREAD

**Issue by 0ge** [Marus/cortex-debug#101]
**Steps to reproduce**
1. Start new debug session.
2. Device is halted
3. Click Run
4. Application starts running

**Expected results**
After step 4 the program can be debugged (i.e. paused, restarted, etc).

**Actual results**
After step 2, only Pause, Restart and Stop are available. Only Stop has any effect (which stops the debug session).

**Workaround**
 - Open the Debug Console and hit Enter.
 - Add `"runToMain": true` to configuration (@Gigaclank)

**Environment**
- VS Code 1.18.2 (since 1.18.0)
- Cortex-Debug 0.1.21
- Configuration:
```
"cwd": "${workspaceRoot}",
            "executable": "<path/to/file>",
            "name": "Debug",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "device": "nRF52832_xxAA",
            "interface": "swd",
            "svdFile": "${workspaceRoot}/vendor/nRF5_SDK_12/svd/nrf52.svd",
            "swoConfig": {
                "source": "probe",
                "enabled": true,
                "swoFrequency": 4000000,
                "cpuFrequency": 0,
                "decoders": [
                    {
                        "port": 0,
                        "label": "SWO Output",
                        "type": "console"
                    }
                ]
```

**Comment by Gigaclank** [comment]
found a solution for me.

try adding in "runToMain": true,

**Comment by 0ge** [comment]
Worked as well! (Still not the desired behaviour for me though)

**Comment by Marus** [comment]
By default (unless runToMain is set to true; in which case it sets a temporary breakpoint at main and runs until it gets a stop event) it will not start the processor at all after flashing (effectively leaving you at the address pointed to by the reset vector). The reason this doesn't happen on reset is that breakpoints may have already be set and there may not be any hardware breakpoints available - making the behavior unpredictable (for fresh launch we haven't set the breakpoints into GDB yet so we can assume at least one available breakpoint).

As to your issues here - I'm wondering if it may be due to the binary blobs that are in your firmware (at least I'm assuming the nRF52 is similar to the nRF51's that have a large amount of functionality provided by binary blobs in Nordic's SDK - but I haven't worked much with Nordic's gear myself). I would have thought that it would have presented you with the disassembly of the startup code which you could step through, but could be some issue there that I haven't seen before depending on what GDB is able to disassemble.

Even if you can't use runToMain functionality on reset - you should in theory be able to manually set a break point at main and then click the continue button to have it run to main. Makes it a two step - but may work as a work around.
