### ISSUE TITLE
st-link V3 support

### ISSUE THREAD

**Issue by EU1KY** [Marus/cortex-debug#228]
There is no way to debug latest STM32 Discovery boards in VS Code because ST-Link V3 is not supported by debugging extensions. Appropriate GDB server has appeared recently: EBLink https://github.com/EmBitz/EBlink . Could you please add EBLink GDB Server support?

**Comment by MabezDev** [comment]
Openocd has had support for stlink v3 since december 2018: https://github.com/ntfreak/openocd/commit/0bad9a42a3b7a3160b264b6d05934c30d8482bf5

You may have to use openocd from git or something more recent than the last release.

**Comment by Marus** [comment]
I would suggest that you try out the OpenOCD support as pointed out by @MabezDev 

I'm hesitant to try and get things work with the EBlink software you pointed out because 1) it is not available on all platforms we support (namely macOS, which is also my primary development environment) 2) it is not open source - meaning there is little possibility for getting it running there and 3) I currently do not have anything with an ST-Link V3 to test it against.

**Comment by timblakely** [comment]
Just confirming that I've been using the V3 on a NUCLEO-G474RE just fine with it (after applying [this patch](http://openocd.zylin.com/#/c/4807/) that I expect to be merged shortly.

**Comment by PhilippHaefele** [comment]
Hi,
It seems that this ticket is also fixed in the meantime. OpenOCD has support in for a while now and Cortex Debug also has support for ST-Link V3. The issue with the shared libraries seems to be handled in #354. So good to close this one 🙂

**Comment by haneefdm** [comment]
Thanks, @PhilippHaefele
