### ISSUE TITLE
More error output from server

### ISSUE THREAD

**Issue by johnjiabinzhang** [Marus/cortex-debug#25]
At the moment the output from server (st-util etc.) as been piped, and is pretty silent. It can be difficult to see what happened if there was an error (e.g. Timeout). It may be a good idea to direct the output to the OUTPUT tab.

**Comment by Marus** [comment]
In most cases all output from the GDB server should be send to the “Adapter Output” view in the Output tab. st-util on windows does seem to have some problems with it not being able to capture the output at all - so that doesn’t work unfortunately. Still looking for a workaround. 

On other GDB servers, and I believe st-util on macOS and Linux, all the output should be captured and displayed.

**Comment by johnjiabinzhang** [comment]
I think it might be because st-util outputs stuff on stderr rather than stdout.

**Comment by Marus** [comment]
It should be collecting both stderr and stdout and sending them both to the same output stream. On OS X and Linux it should all get collected (at least it does on my Ubuntu and OS X setups) - for example here is the Adapter Output that is collected from a launch on my OS X machine (https://pastebin.com/9WSscxG2)

Unfortunately there is an issue with ST-Util on Windows where I cannot collect any of the output - this is the same reason I had to implement the work around for the launch timeout issue you had found. Until I can find some solution to the st-util on Windows issue I can't do anything about this problem either.

**Comment by johnjiabinzhang** [comment]
It doesn't seem to work on my macOS though, as in the output is not displayed in the `OUTPUT` tab nor `DEBUG CONSOLE` tab.

**Comment by johnjiabinzhang** [comment]
Ah, sorry, ignore what I said, I found it.
