### ISSUE TITLE
JLinkGDBServer has changed name in latest release

### ISSUE THREAD

**Issue by microwavesafe** [Marus/cortex-debug#43]
The name of the executable on Linux has changed to
JLinkGDBServerCLExe
from
JLinkGDBServer

**Comment by Marus** [comment]
For the time being you can set the path in the user setting (cortex-debug.JLinkGDBServerPath) - as that path includes the executable name. For the next update I’ll try to add something that searches on the path for both variations of the name - so that it will work with either version if it is on the system path.

**Comment by microwavesafe** [comment]
Ah perfect thanks, I'll use that.

**Comment by Marus** [comment]
Update has been pushed to the market place. Will check now for both versions of the name - so should work with the newer version if it is available.
