### ISSUE TITLE
Mac OS not hitting breakpoints with ST-Link

### ISSUE THREAD

**Issue by samchamberlin** [Marus/cortex-debug#434]
Using this plugin with ST-Link and breakpoints don't seem to be working on macOS Big Sur. I compiled with full debug enabled. In the debug console I get this output from the "info breakpoints" command: 
![Screen Shot 2021-05-05 at 4 41 40 PM](https://user-images.githubusercontent.com/46569551/117218649-c677d400-adc0-11eb-9940-d5aee0ec8904.png)

Has anyone run into this problem? Any help is appreciated!

**Comment by haneefdm** [comment]
Can you make it work using the command-line tools? Breakpoints, while we set them from the extension, we just wait until gdb (which waits on st-util) to report a hit. If that doesn't work, neither will Cortex-Debug

**Comment by samchamberlin** [comment]
Thanks @haneefdm, here's the debug console with `showDevDebugOutput` set to true:
![Screen Shot 2021-05-06 at 8 39 06 AM](https://user-images.githubusercontent.com/46569551/117317205-8a875200-ae46-11eb-9ad0-5271e770991c.png)

It seems to run just fine - the STMicrocontroller shoots serial output out to me correctly. I'm not familiar with setting breakpoints using command-line tools if that's what you mean. 

Thanks for the help!

**Comment by ubidefeo** [comment]
@samchamberlin 
do you happen to have your breakpoint right before the end of a function or at the exit point of a code block?
I have noticed that if the breakpoint is placed as follows

```c++
if(condition){
   counter++;
   secondCounter--;
   thirdCounter += counter; // place breakpoint here
}
```

it won't be caught.
same happens when you have two consecutive breakpoints and on the first one you do `step into`: when doing `continue` it won't stop at the second breakpoint
