### ISSUE TITLE
Periodic update register value at runing

### ISSUE THREAD

**Issue by zhiyishou** [Marus/cortex-debug#473]
Cortex-debug register/variable value will be unavaiable at runing mode, some dynamic debug operation with variable is needed acctually, Keil offers a "Periodic update window" option to poll all data fresh,  is there a same function close to Keil in Cortex-debug?

Thanks

**Comment by haneefdm** [comment]
Sorry, no, there is no such thing in Cortex-Debug. Only way to do this with GDB is to pause the program, read the registers and let it continue. But this causes a whole lot of activity in the entire GUI (all windows get updated/painted), hundreds/thousands of memory reads occur, and is not wise. Keil is able to do that because they control the entire GUI. We don't, not that easily anyway. I have used that feature myself in Keil Vision and did not find it that useful anyways. Watch windows, yes but not registers and it is pretty invasive.

You can use things like RTT/SWO to output interesting items that are streamed to the VSCode GUI. Sure you have to modify your source code but yes.
