### ISSUE TITLE
J-Link debug with multiple binaries doesn´t work

### ISSUE THREAD

**Issue by AlbinHjalmas** [Marus/cortex-debug#504]
**Scenario:**
Im currently developing firmware for a Cortex-M based device. The firmware consists of a bootloader and an application. I am using a J-Link debug probe for programming and debugging my device. Debugging the bootloader located at flash memory start address is working as expected. Debugging the Application, located at some offset from the flash memory start address i not working as expected.

**Problem:**
The problem arise when launching a debug session for the application. This is because of the following launch sequence:

1. **halt execution**
2. **reset processor**
3. **program executable into flash**
4. **reset processor**
at this step the processor will initiate PC with the start address of the flash memory which will contain the bootloaders stack pointer followed by the address to the bootloaders reset handler and cosequently launch the bootloader.

The problem arise at step 4. Step 4 is actually not needed for normal boot of the processor and, in my case, actually breaks my debug session.

**Possible solution:**
 My local solution is to remove the 4th step from the launch sequence (i.e. line 60 in the figure below). 
![Capture](https://user-images.githubusercontent.com/26245600/136778838-95e53d09-36b5-44da-8368-bc5ff17dcd15.PNG)
Maybe it would be wise to have a few optional launch sequences?

**Comment by haneefdm** [comment]
@AlbinHjalmas There are thousands of ways you can use any gdb-server including JLink. What is provided there is the default that works for most people. So, this is not going to change as it will break what has been working for years.

Please do not remove that line or you will forever have to keep doing that. For some, the `target-download is not the right thing (for me for instance because my elf file is incomplete)

This is the reason why we provide facilities for you to create your own recipes.  In launch.json you can use `pre', 'post', and 'override' command-sets to change the default behavior.

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

If you are still having issues, please get back to us.
