### ISSUE TITLE
How can I actually use this extention

### ISSUE THREAD

**Issue by jancoow** [Marus/cortex-debug#523]
Like the title stated, how can I actually use this extention? I've no clue how I can enter the view. I currently start my openOCD / GDB with this launch configuration:

```       {
            "name": "Attach",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/output.elf",
            "cwd": "${workspaceRoot}",
            "debugServerArgs": "-f /home/janco/openocd.cfg -c init -c \"reset init\"",
            "serverLaunchTimeout": 2000,
            "filterStderr": true,
            "filterStdout": false,
            "serverStarted": "target halted due to debug-request, current mode: Thread",
            "setupCommands": [
                { "text": "-target-select extended-remote localhost:3333", "description": "connect to target", "ignoreFailures": false },
                { "text": "-file-exec-and-symbols ${workspaceRoot}/build/output.elf", "description": "load file", "ignoreFailures": false},
                { "text": "-interpreter-exec console \"monitor halt\"", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"set remote hardware-breakpoint-limit 4\"", "ignoreFailures": false },
                { "text": "-interpreter-exec console \"set remote hardware-watchpoint-limit 2\"", "ignoreFailures": false },
            ],
            "linux": {
                "MIMode": "gdb",
                "MIDebuggerPath": "/usr/bin/arm-none-eabi-gdb",
                "debugServerPath": "/usr/local/bin/openocd"
            },
            "logging": { "engineLogging": false, "trace": false, "traceResponse": false },
        }

```

But this extention doesn't seem to popup. I'm unable to enter the memory view.

**Comment by haneefdm** [comment]
This is because you are using Microsoft's CPP debugger extension which is good for desktop. Use

```
    "type": "cortex-debug",
```
And, most of what I see in your launch.json is `cppdbg` specific. When you open `launch.json`, do you see a button
![image](https://user-images.githubusercontent.com/41269583/141129349-03082d79-3224-4c62-83d5-68c1b7cd8a58.png)
Click on that and you can get select Cortex-Debug and then you can select one of the templates.

See https://github.com/Marus/cortex-debug/wiki and https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

There are commands available from the command-pallette to invoke a memory viewer (starts with `Cortex-Debug: `
