### ISSUE TITLE
visualizerFile not supported

### ISSUE THREAD

**Issue by seppeon** [Marus/cortex-debug#530]
This is more of a feature request, but it seems a very useful one!

visualizerFile are not currently supported. They allow better viewing of various library types, such as string_view and various containers.

**Comment by haneefdm** [comment]
I think this is beyond our scope. If GDB or VSCode core had support for this, that would be one thing. I have used it on C++/C# applications in VStudio before so I know what it is.

We don't even control much of the UI in VSCode. We are just a backend. If you have some reference implementations in VSCode I can take a look but otherwise, I have to close this enhancement request.
