### ISSUE TITLE
Support VS Code log points

### ISSUE THREAD

**Issue by Rehcsif** [Marus/cortex-debug#542]
Currently when using log-points in VS Code + Cortex Debug they act like normal break points, no log message is printed in the debug console. Is it possible to support log points when using cortex-debug plugin? 

I do not know if I get all the details, but here's my thought:
Using Eclipse and "dynamic printfs", when debugging a STM32F4 application via Segger JLink, seems to have the same effect as VS code's log points should have. I do not know how Eclipse manages to support them, but GDB seems to support this feature:
https://sourceware.org/gdb/current/onlinedocs/gdb/Dynamic-Printf.html#Dynamic-Printf

Also the machine interface of GDB supports dynamic printfs: "-dprintf-insert"

Therefore the question: Is it possible to support logpoints via Cortex-Debug Plugin?

**Comment by haneefdm** [comment]
Thanks for letting us know. Yes, it should be possible especially because they are supported by the Debug Adapter Protocol that VSCode uses and we have to conform to.

https://microsoft.github.io/debug-adapter-protocol/specification

If all the pieces are there, we should be able to add support. But this generally means trial and error on how all the pieces fit together and it will not be as clear as one might think.

**Comment by haneefdm** [comment]
Added to my todo list.

https://github.com/Marus/cortex-debug/blob/master/TODO.md

**Comment by haneefdm** [comment]
Just added logpoints. It is available as a preview release (v1.3.0). You can install it directly from within VSCode but you have to enable it. Please let me know. Since it is a preview, we can still make some changes. Also see ChangeLog for info

All releases with an odd minor number are pre-releases as per MS for using their pre-release mechanism. So, all 1.3.x will be pre-releases and 1.4.x will be final releases.

**Comment by hongshui3000** [comment]
If the expression is written incorrectly, the program cannot be stopped
log points
![image](https://user-images.githubusercontent.com/25566498/151479077-eccd7174-0004-4ba5-aed6-499c5f5359b5.png)
log：
```
Debug-212: Enqueuing {"command":"disassemble","arguments":{"memoryReference":"0x000003bc","offset":0,"instructionOffset":-200,"instructionCount":400,"resolveSymbols":true},"type":"request","seq":212}
Debug-212: Dequeuing...
Debug-212: Elapsed time for Disassembly Request: 003 ms
Debug-213: Enqueuing {"command":"disassemble","arguments":{"memoryReference":"0x000003bc","offset":0,"instructionOffset":-200,"instructionCount":400,"resolveSymbols":true},"type":"request","seq":213}
Debug-213: Dequeuing...
Debug-213: Elapsed time for Disassembly Request: 004 ms
A syntax error in expression, near `int)0xc3050004'.

```

**Comment by haneefdm** [comment]
Thanks, I will take a look. I actually have no clue what gdb actually expects as there is no grammar specified. I did make some intentional errors but it did not do anything disastrous. So no clue why the program cannot be stopped. Breakpoints fail all the time (logpoints are just breakpoints). It let me know it was invalid and breakpoint did not get set and the GUI indicated that as well.

I will try your exact message. But tomorrow.

**Comment by haneefdm** [comment]
Nope, I can't duplicate it.
```
60-break-insert "/Users/hdm/rtt/Hello_World/main.c:181"
61-dprintf-insert "/Users/hdm/rtt/Hello_World/main.c:184" "Value of counter is %x\n" *(int*)0x01000000
-> 60^done,bkpt={number="6",type="breakpoint",disp="keep",enabled="y",addr="0x100090a8",func="main",file="main.c",fullname="/Users/hdm/rtt/Hello_World/main.c",line="181",thread-groups=["i1"],times="0",original-location="/Users/hdm/rtt/Hello_World/main.c:181"}
```
What version is your gdb? Mine is 10.3
`GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.07) 10.2.90.20210621-git`
Also tried with 8.3
`GNU gdb (GNU Arm Embedded Toolchain 9-2020-q3-update) 8.3.1.20191211-git`

**Comment by Rehcsif** [comment]
Thanks a lot for adding this feature. Tried it and for me it seems to work as expected.

**Comment by haneefdm** [comment]
Yes, I am able to duplicate it now. Problem is not setting the breakpoint. It is gdb handling it. When gdb goes past this breakpoint, it prints the syntax error and then it no longer reponds. Regardless how many we ask it to. You can see that below. There is no reponse to `-exec-interrupt`..

Moral of the story, don't make mistakes when you ask for logpoints. We don't have a parser for this and we rely on gdb to do its thing. You can file a bug with the gdb folks.

```
-> =breakpoint-modified,bkpt={number="2",type="dprintf",disp="keep",enabled="y",addr="0x100090ae",func="main",file="main.c",fullname="/Users/hdm/rtt/Hello_World/main.c",line="184",thread-groups=["i1"],times="1",script={"printf \"Value of counter is  %x\\n\",*(*int)0x01000000"},original-location="/Users/hdm/rtt/Hello_World/main.c:184"}
-> &"A syntax error in expression, near `int)0x01000000'.\n"
A syntax error in expression, near `int)0x01000000'.
56-exec-interrupt 
-> 56^done
57-exec-interrupt 
-> 57^done
58-exec-interrupt 
-> 58^done
59-exec-interrupt 
-> 59^done
```

**Comment by haneefdm** [comment]
@Rehcsif You are welcome and thanks for bringing this to our attention. It appears it actually works better than the 'cpptools' logpoint because it doesn't seem they use dprintf. Instead they just print a string at the breakpoint and continue. So, no evaluation of the log message. That was my first implementation as well but, then I decided to use the `dprintf` mechanism

But as you can see, gdb can be unpredictable when you make errors.

I am closing this for now and a note to myself to document issues with it.
