### ISSUE TITLE
Is there any plan to support mem and register write window？

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#551]
Is there any plan to support mem and register write window？
It seems that the following registers cannot be written through the window, and mem has not found any place to write directly, except for using the gdb command

![image](https://user-images.githubusercontent.com/25566498/147321970-b0d92622-27a4-4193-b7a1-3dae9558aa48.png)

**Comment by PhilippHaefele** [comment]
Yes this is at least on the TODO list (https://github.com/Marus/cortex-debug/blob/master/TODO.md).

But not sure when @haneefdm will work on that

**Comment by haneefdm** [comment]
This may be something some people may not know. Using the Debug Console to interact directly with GDB. The bottom part is the input section and you can any gdb command so long as you don't drastically change the debugger state (like killing it). You can do the following
```
set $r0 = 0xdeadbeef
set mystruct.myfield = 23
print mystruct.myfield
call myFuncion(myArg)
```
My syntax may be wrong at places. Note: All register names a prefixed with a `$` and are pre-defined by gdb

![image](https://user-images.githubusercontent.com/41269583/147349909-2d239381-c3ae-47ad-9dae-90570f01545d.png)

This is what we did when we didn't have good Visual debuggers and still do since they don't support every possible thing I want to do.

That bottom input part of the window is called `REPL` (Read-Eval-Print Loop) 
https://code.visualstudio.com/docs/editor/debugging#_debug-console-repl

Some debuggers (Python, JavaScript, etc.)
