### ISSUE TITLE
ATSAME54P20A svd not loading

### ISSUE THREAD

**Issue by preetham05** [Marus/cortex-debug#566]
I am not able to load ATSAME54P20A svd file which i obtained from ATMEL website. Could you please advice me on how to overcome this issue. 
[svd.zip](https://github.com/Marus/cortex-debug/files/7853625/svd.zip)

**Comment by haneefdm** [comment]
There was an issue that was fixed a while ago and it seems to have fixed your issue. Unfortunately, the fix is only available in a preview release.

If you want to try it out, you can enable/install preview releases in VSCode
![image](https://user-images.githubusercontent.com/41269583/149173951-08df4a69-b9df-43bc-815f-28f96d02468c.png)

It will be a couple of weeks before an final release is made.
