### ISSUE TITLE
Do I need to provide the load address if I use “loadFiles” to load bin?

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#591]
1.Do I need to provide the load address if I use “loadFiles” to load bin?

2.Does "executable" still work if "loadFiles" is used?

3.Can multiple binaries be loaded into memory using loadfiles? different addresses

**Comment by haneefdm** [comment]
1. Nope. You must be new to this. All formats that gdb and gdb-servers support already have the load address in it. If needed you do it when generating the files. Just take a look at intel hex format.
2. Yes gdb (and us) still need the "executable". Without it, nothing works. No meaningful stack traces, no variables names, etc.
3. Yes, you can load multiple binaries. This happens for many reasons -- multi-core is one example. There are others. Item#1 should answer about addresses. If you have overlapping addresses, then order also matters.

You can also debug without loading anything. That is maybe because someone else programmed the device or it is programmed not via SWD but over-the-air or over ethernet or from another chip on the board. I worked with one chip like that. Executable still needed.
