### ISSUE TITLE
PR with a Cortex support to original @WebFreak001 repository

### ISSUE THREAD

**Issue by ivankravets** [Marus/cortex-debug#6]
Firstly, thank you very much for this initiative for the better support for Cortex MCUs! 

We (@PlatformIO) currently use original https://github.com/WebFreak001/code-debug extension for our [PIO Unified Debugger](http://docs.platformio.org/en/latest/plus/debugging.html). How is difficult to make PR to @WebFreak001 repository just with the Registers/Peripheral features? 

Thanks in advance!

**Comment by Marus** [comment]
While I will be submitting a PR to @WebFreak001 (once I finally get some time) to cover a number of bugs I've found and fixed (and I'm quite willing for those bug-fixes to be public domain), I have changed the underlying systems quite substantially and don't think it would be feasible to bring the  peripheral register features back to his extension easily. (I also don't think the peripheral register features are really suitable for an extension that is not focused on Arm Cortex Debugging)

A processor core register feature is more generic - so @WebFreak001 may be interested in implemented something like that on his own; but I don't think I will be preparing a Pull Request for that myself, at least not right away.

Here are the bug fixes that I plan to submit a PR for once I get time (hopefully sometime in the next week or so):
* Some bugs in the MI parsing and GDB expansion code (parsing can be incorrect if there are empty strings in the results, or floating point values in structs/objects).
* Issue with it updating the value for the root of an object/array when an element of that object/array changes
* Issue with it incorrectly clearing breakpoints when setting them in a second file.

(Might also be a other minor bugs I can't think of at the moment that I will back port as well)

But I would like to thank @WebFreak001 for his project - his MI parsing/interaction code made it much quicker to get off the ground running with this project than it would have been otherwise.
