### ISSUE TITLE
Does the extension seem to be requesting gdb disassembly when the disassembly view is not open?

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#604]
log
```
Debug-37: Enqueuing {"command":"disassemble","arguments":{"memoryReference":"0x000624f8","offset":0,"instructionOffset":-200,"instructionCount":400,"resolveSymbols":true},"type":"request","seq":37}
Debug-37: Dequeuing...
Debug: Gdb command: -data-disassemble -s 0x000620cc -e 0x000623a4 -- 5      728 bytes  (__udivmoddi4)
Debug: Gdb command: -data-disassemble -s 0x000623a4 -e 0x00062ce8 -- 5     2372 bytes  (assert_err)
Debug: data-disassemble -s 0x000620cc -e 0x000623a4 -- 5 => Found 253 instrunctions. 0 with source code, 253 without
Debug: data-disassemble -s 0x000623a4 -e 0x00062ce8 -- 5 => Found 921 instrunctions. 921 with source code, 0 without
Debug-37: Elapsed time for Disassembly Request: 4545 ms

```
This affects debugging performance, other command operations are affected, when I pause debugging, send other gdb commands

**Comment by haneefdm** [comment]
Yup. Extension by itself does not do it. But VSCode does it. Happens if the program first stops in a place with no source code. I have seen other instances when VSCoede requests disassembly even when there is source code and I have just closed the disassembly window.

Does not have a perceptible effect on performance though because all disassembly requests are queue and occur asynchronously

**Comment by haneefdm** [comment]
> This affects debugging performance, other command operations are affected, when I pause debugging, send other gdb commands

A. I don't know if this true. Once the session starts, I don't see any anamolies. Just at the start of the session on certain applications. Btw, Eclipse does this too.
B. We never initiate a Disassembly operation. No reason to.

**Comment by hongshui3000** [comment]
Maybe it's a issue with my computer's performance.I close this issue.
