### ISSUE TITLE
Interleaved Assembler and Source

### ISSUE THREAD

**Issue by stevenj** [Marus/cortex-debug#64]
Where the debugger knows that source exists, It would be nice if the Assembler view, also showed the source interleaved with the disassemble.  This should be selectable, so you can have raw disassembly, or interleaved.  The default should be interleaved.

**Comment by Stephenmccaul** [comment]
The ability to show the current source with it's disassembly even if in different windows would be really useful. (anything to get closer to Visual Studio's contextual go to disassembly that has interleaved source as suggested). This is one of the few features that regularly gets me back in VGDB instead of Cortex-Debug. 

The default behavior when selecting "forced" when debugging in C that replaces the current source window with the disasm window rather than opening it in a new window is frustrating as I almost always want to see both at the same time so just being able to have the source and the disasm open at the same time would be a partial fix toward this suggestion.

Even a hot key to quickly go back and forth between C and the disasm would help. I wasn't able to get a hotkey working to toggle without going through the Auto/Forced menu.

**Comment by Evaneee** [comment]
hope to watch current code and disassembly together， very useful for me

**Comment by mayjs** [comment]
Just for your interest, gdb can interleave the source lines by passing `/m` to the `disassemble` command, so I think a minimal implementation would be to add some configuration option to enable this flag. For me, this would be good enough, without this the disassembly can be hard to read.

**Comment by PhilippHaefele** [comment]
Thanks to @haneefdm the extension has now (since prerelease version V1.1.7) support for the VSCode Disassembly view. There's a setting in VSCode named "Show source code" which should view interleaved code and disassembly (didn't tested it due to lack of setup right now).

BTW Hi @mayjs. Had several looks over this issue and haven't recognized that you commented that issue. See/hear you on monday 😄

**Comment by haneefdm** [comment]
We always knew gdb can interleave but the presentation/UI/UX, hooking it up to the call-stack, breakpoints etc., single stepping, etc., we cannot do from the extension for lack of APIs. This is why I was waiting for MS to do their thing. I originally worked on the MS spec for the backend almost two years ago. I don't think it is still right and I am seeing some issues with getting WRONG disassembly from gdb because of instruction alignment and how requests come from VSCode.

**Comment by haneefdm** [comment]
I also see another problem with this. Disjoint memory regions holding code. Happens a lot in embedded. Secure, non-secure address spaces, external flash, some code running flash/external-flash and some in RAM, etc. Not clear how MS will deal with this. We know our backend can... we will have to see what the front end will do with it. This is never an issue in normal/native programs which is what the MS people are used to.

**Comment by PhilippHaefele** [comment]
@haneefdm As we have a release with new disassembly view now, we can close this one
