### ISSUE TITLE
No valid SVD filepath

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#713]
![image](https://user-images.githubusercontent.com/25566498/182529754-7029bd34-4be5-4841-baad-d03ab896a76e.png)
No valid SVD filepath.
I'm using CORTEX debug and Microsoft's Embedded tool, but the embedded tool svd display has some issues, I don't know if it's a issue with cortex debug or its own problem.
launch config
```
            "svdFile":"./STM32L0x0.svd",
            "svdPath":"./STM32L0x0.svd",
```
cortex debug svd works fine

**Comment by haneefdm** [comment]
I don't know, but you should file an issue with them. It worked for me and I didn't do anything special. Not in our extension, or theirs, or my launch.json other than just using their method of specifying it.

Contrary to what people think, the SVD is a beast of a thing to parse and make sense of, mainly because it changes all the time. Maybe it is stable now. We are several years behind and the format moved on with tons of new stuff. I don't have an army of people to keep track. So, I was glad MS took up the mantle. Isn't that nice? So, please help them.

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/182746466-b31aefab-0ce0-4b65-969a-0a9db5eb0f82.png)
![image](https://user-images.githubusercontent.com/25566498/182746485-d560fa5c-375f-4f1f-83fe-30440269ee1a.png)
Can these two functions currently support hiding? Because it is a bit repetitive with other functions. After hiding, the debugging interface will become more concise

**Comment by haneefdm** [comment]
Yes, you can right-click and hide any panel. Also, click on the there dots `...` on top right.
