### ISSUE TITLE
Attach to running code

### ISSUE THREAD

**Issue by mike-rob** [Marus/cortex-debug#75]
Using the J-link and eclipse I can attach a debugging session to code already running on a chip. Would it be possible to add this option to you extension? I think basically it connects but skips the programing step. It normally has a name like `Attach only` or `Attach to a running target`

I really like your extension as it allows me be able to move away from heavy and buggy eclipse biased IDEs. :+1:

**Comment by Marus** [comment]
You can already do this - in your launch.json launch configuration use `"request": "attach"` instead of `"request": "launch"`.

A few other options may need to change as well - as they may not be applicable to attach vs. launch type requests (for example "runToMain" doesn't exist in attach), and the pre/post LaunchCommands are renamed to pre/postAttachCommands.

**Comment by mike-rob** [comment]
Thanks, did not see that. Thanks! :+1:
