### ISSUE TITLE
get toolchain settings from cmake

### ISSUE THREAD

**Issue by JojoS62** [Marus/cortex-debug#774]
I'm using cmake-tools extension and this is the master for finding or selecting a toolchain. Can these settings for compilerpath, gdb etc be used in the launch configuration? This will also simply the setup for different OS.

**Comment by haneefdm** [comment]
I have zero experience with the "CMake Tools" extension from Microsoft. What I know is that people are using it to import various things from cmake using commands (there are 71 of them). You can also use cmake settings instead of commands ([see launch.json doc in vscode](https://code.visualstudio.com/docs/editor/variables-reference)). For instance

```
            "executable": "${command:cmake.launchTargetPath}",
```
https://github.com/microsoft/vscode-cmake-tools/blob/a00c339cef191fb9bae64922713189bf64d994b0/docs/debug-launch.md

Most settings can be overridden in launch.json.

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

Search for path/chain. `armToolchainPath` is your most important one for gdb toolchain.

I would post additional questions about CMake commands to either StackOverflow or the "CMake Tools" extension repo
