### ISSUE TITLE
Duplicit 'reset halt'/'halt' in OpenOCD launch/attach

### ISSUE THREAD

**Issue by tom-van** [Marus/cortex-debug#778]
OpenOCD supports issuing gdb 'load' command without any previous/following reset commands.
To achieve this OpenOCD has two events, preset to 'reset init' and 'reset halt' for each target:
https://github.com/openocd-org/openocd/blob/master/src/target/startup.tcl#L212-L213

Also 'halt' is issued on gdb attach since 2018
https://github.com/openocd-org/openocd/blob/master/src/target/startup.tcl#L214

The cortex-debug extension does the same on its own:
https://github.com/Marus/cortex-debug/blob/master/src/openocd.ts#L102-L103
https://github.com/Marus/cortex-debug/blob/master/src/openocd.ts#L110

It creates an useless duplicity.
If OpenOCD 'gdb-flash-write-end' event is customised to enforce some specific MCU setting, it is likely lost by the following reset from cortex-debug. Also if other events are customised they probably will not work as expected in combination with the commands sent from cortex-debug.

Could you please drop these duplicities?

**Comment by haneefdm** [comment]
I see what you are saying but I am not going to change this. It has been this way forever in our extension. Don't forget that there are half a dozen forks of openocd and we have no idea which ones will break

Did you know that multiple loads are possible and that also causes multiple events?  I should be able to rest multiple times and it should still be safe. A restart also does a reset. So, your event handlers should also expect this.

The halt after attach is needed so we can set breakpoints and other maintenance things for VSCode. Also, it is superfluous because gdb expects the gdb-server itself to do that so it can read the PC/SP/Stack. This is normal and not going to change.

We have provided numerous ways to customize these sequences since one size does not fit all. We also documented the same in our [Wiki](https://github.com/Marus/cortex-debug/wiki/Cortex-Debug:-Under-the-hood) and here

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md
