### ISSUE TITLE
Core specific breakpoints possible?

### ISSUE THREAD

**Issue by ch-ey** [Marus/cortex-debug#787]
Hi,

I am debugging an MCU with multiple CPUs (CM0+, CM4) and it basically works fine apart from the breakpoint behavior. Both cores share the same driver source files, and when I set a breakpoint, both cores halt at the respective instruction. It does not seem to be possible to limit the breakpoint to a given core.
Is that a limitation of the extension or Microsoft's Debug Adapter Protocol? With my limited knowledge I had a look at the [SetBreakpoints request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetBreakpoints) and it does not seem to support an argument to specify the targeted "thread" in contrast to for example the [Next request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Next) for single stepping.
Is it possible to achieve core specific breakpoints somehow? I assume other functionality e.g. variable watch/modification suffers from the same problem?

Thanks

**Comment by haneefdm** [comment]
> Is it possible to achieve core specific breakpoints somehow? I assume other functionality e.g. variable watch/modification suffers from the same problem?

Yes, but NOT when you share source code. This is a limitation of the VSCode UI. Neither the DAP nor this extension is involved.  Note that breakpoints can be manipulated with no debugger running. They are saved/restored with the workspace, etc.

Are you using PSoC6 by any chance?

You can create copies of the shared source code, one for each code, and now VSCode will treat them as totally separate files....

Your variables are stack-frame specific so that is not affected. Watch expressions are global and there are no workarounds for that ... but all watch variables are evaluated in the stack-frame-specific context. So, that is not much of a problem.
