### ISSUE TITLE
"Could not continue: variable object not found (from var-assign val ...)" when trying to change variable

### ISSUE THREAD

**Issue by JWo1F** [Marus/cortex-debug#79]
![2018-08-08 01-12-25](https://user-images.githubusercontent.com/1540715/43805472-846b4bec-9aa8-11e8-8625-e3d8dbf5f31f.png)

**Comment by PhilippHaefele** [comment]
Setting local variables in this place worked for me with v1.6.10 (J-Link, STM32 CPU).

As this issue is very old and there's no further information about the setup, i can't further test this.

@haneefdm I think we can close this one for now

@JWo1F IF you still see this issue with the current released version, please provide further information, so we'll be able to further investigate
