### ISSUE TITLE
Unable to step into code

### ISSUE THREAD

**Issue by Joebeazelman** [Marus/cortex-debug#852]
I'm using the latest version of cortex-debug with an STLink V2 version 1.9 BMP build. The binaries I'm debugging are statically linked and contain symbolic information. I'm able to step over the code as well as add watches and halt at breakpoints, but can't step into any of functions. The **step into** behaves exactly like **step over**. At the very least, I expect it to step into disassembled code.

I tried to set *Just My Code* to false in my launch configuration hoping that although it's a PyDebug setting, it might be a common among all VSCode debuggers. Unfortunately, it's not a valid launch setting for cortex-debug.

What could be the cause?

**Comment by haneefdm** [comment]
Step commands only work with code that has source line info available -- even if the source file does not exist. However, you can do instruction-level steps instead of the default VSCode step which is code-level.

You can do this in the disassembly window managed by VSCode (we supply the instructions). See

https://github.com/Marus/cortex-debug/wiki/Disassembly-Debugging

If you have issues with the UI, then that is not us, please file issues with the VSCode team. We only supply the raw data.

**Comment by haneefdm** [comment]
I wish VSCode had `stepi/nexti` built into their Debug Toolbar buttons. For instance, Shift+Button could mean `stepi` instead of `step`. Those buttons do not belong to us, so we can't change their behavior.

**Comment by haneefdm** [comment]
I am closing this as it is not something we can fix/address
