### ISSUE TITLE
"Disconnect" (without Suspend) leaves MCU halted

### ISSUE THREAD

**Issue by lijon** [Marus/cortex-debug#894]
**Describe the bug**

I'm using openocd with an STM32G071 Nucleo board (ST-Link/V2-1 embedded debug probe).
I'd like to be able to end a debug session but keep the MCU running, but it seems there's no difference between "Disconnect" and "Disconnect and Suspend".

**To Reproduce**

1. Start debug session
2. Click on the arrow besides the Stop button
3. Choose "Disconnect" instead of "Disconnect and Suspend"

**Expected behavior**

Debug session ends and MCU keeps running.

**Actual behavior**

Debug session ends and MCU is halted. Pressing the RESET button on the Nucleo board doesn't even help, it needs to be power-cycled to get it back.

**Additional info**

It should be possible in theory, because if I pause the debugger, then enter in the debug console:

```
mon resume
```

,and then close the debugger, it does detach and leave the MCU running.

**Environment:**

 - Cortex-Debug Version 1.11.2
 - OS: macOS
 - GDB/Compiler Version: GNU Arm Embedded Toolchain 10.3-2021.07) 10.2.90.20210621-git

**`launch.json`**

```
"version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceRoot}",
            "executable": "./build/myProgram.elf",
            "name": "Debug with OpenOCD",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "interface": "swd",
            "device": "STM32G071",
            "configFiles": [
                "interface/stlink-v2-1.cfg",
                "target/stm32g0x.cfg"
            ],
            "svdFile": "../STM32G0_svd_V1.3/STM32G071.svd",
            "searchDir": [],
            "runToEntryPoint": "",
            "showDevDebugOutput": "none",
            "preLaunchTask": "${defaultBuildTask}",
            // "liveWatch": {
            //     "enabled": true,
            //     "samplerPerSecond": 2
            // }
            "postRestartCommands": [
                "load",
                "monitor reset run"
            ]
        }
    ]
}
```

**`Debug Console`**

```
16-exec-interrupt
-> 16^done
-> ~"\nProgram"

Program
-> ~" received signal SIGINT, Interrupt.\n"
 received signal SIGINT, Interrupt.
-> ~"MUX_EN_Timer_Elapsed () at Src/main.c:527\n"
MUX_EN_Timer_Elapsed () at Src/main.c:527
-> ~"527\t    mux_addr_index++;\n"
527	    mux_addr_index++;
-> *stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt",frame={addr="0x20001218",func="MUX_EN_Timer_Elapsed",args=[],file="Src/main.c",fullname="/Users/lijon/Coding/STM32/PolyVoiceBoardG071/Src/main.c",line="527",arch="armv6s-m"},thread-id="1",stopped-threads="all"
mi2.status = stopped
17-break-delete
-> 17^done
18-target-detach
-> =thread-exited,id="1",group-id="i1"
-> =thread-group-exited,id="i1"
-> ~"[Inferior 1 (Remote target) detached]\n"
[Inferior 1 (Remote target) detached]
-> 18^done
19-target-disconnect
-> 19^done
-gdb-exit
-> ^exit
GDB session ended. exit-code: 0

```

**Comment by haneefdm** [comment]
This is an issue with openocd. It is not compliant with gdb for `-target-detach`. In our own company we fixed this for ourselves. If you use the latest version of JLink for instance will work. We are doing the right thing.

Please submit this issue with openocd.

**Comment by lijon** [comment]
I see. As a workaround, is there any preDisconnectCommands hook or similar that I could add `mon resume` to?

**Comment by haneefdm** [comment]
Sorry, there is no workaround that I know that is possible. Otherwise, we would have done it because we know of this issue.

I have seen the source code in openocd and there is no workaround. Period. The stock openocd does not do everything needed to do a proper detach. It needs to

1. Remove all break/watch points (we already do this because of bugs in gdb servers)
2. Resume if the program is halted
3. Clear the debug flags in the ARM debug HW
4. Disconnect from SWD
5. etc.

Even JLink was not compliant until we made them aware. See https://github.com/Marus/cortex-debug/issues/756

**Comment by lijon** [comment]
So do you mean that `mon resume` is not actually working as I expect? (Is it leaving the MCU in some half-debug-state or something like that?)

I assumed the various pre/post command hooks where exposed by this extension, and that it would be possible to add a hook for gdb (or gdb-server) commands to be executed at disconnect?

**Comment by haneefdm** [comment]
Please submit a bug against openocd instead because therein lies the problem. Not here. Just like JLink, it needs to be fixed. They need to clear the entire state. Not just resume.

I am not interested in creating workarounds for this.

**Comment by lijon** [comment]
Done! https://sourceforge.net/p/openocd/tickets/399/

**Comment by mbenkmann** [comment]
I found the fix on StackOverflow:

https://stackoverflow.com/questions/28216278/gdb-and-openocd-reset-or-resume-after-end-of-debugging

Create `openocd-gdb.cfg` containing :

```
$_TARGETNAME configure -event gdb-detach {
    resume
}
```

And add the file `openocd-gdb.cfg` to `configFiles` in your `launch.json`.

**Comment by haneefdm** [comment]
But, this is a bug in openocd. Glad you found a workaround. Other gdb-servers follow the specification set by gdb.

**Comment by dsabala** [comment]
@haneefdm I observed similiar issue with CortexDebug and Jlink config, I have some performance critical application and when I turn off debug session it looks like MCU is halted for a milliseconds and then resumed, however milliseconds is enough to lost some data. 

Should I expect my setting to handle this debug session "Disconnect" without halting MCU or should I give up and live with this fact?

**Comment by haneefdm** [comment]
@dsabala I know the use cases where it is a must never to halt the CPU. Motor control is one.

I gave up on it as too many stars have to align but you can try with a fresh perspective....here is some info

This is a problem with both gdb and gdb-server. GDB will not allow most commands to be sent to it while the program is running. So, we have to halt the target (CPU) temporarily to issue the `detach` command. Or else, we can never detach or disconnect.

GDB ALLOWs all commands to be sent to it (that it forwards to the gdb-server)  if you put gdb in Non-stop mode, but the gdb-server has to support that. Most don't.

Requirement is that the gdb-server implement a proper detach. openocd (and many others don't). JLink does (we worked with JLink to get this working two years ago). Please read the following

https://sourceware.org/gdb/current/onlinedocs/gdb.html/Asynchronous-and-non_002dstop-modes.html
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Non_002dStop-Mode.html#Non_002dStop-Mode

Most embedded CPUs do not support the gdb-style non-stop mode.

Non-stop also has other side effects as to what happens when you do a `continue` and other commands. All execution related commands only affect the current thread. They are not really side effects but intentional but it causes VSCode (and more importantly cortex-debug) confusion.

[Take openocd as an example (Google Search Results)](https://www.google.com/search?q=openocd+non+stop+mode&mstk=AUtExfC7F1DRfVyo8uWZmIb9sUULmnM_TygAalKrp1HCJqkkZlLsmnakmn-nlDjyERpaxyJvn_R5hupkVpQvxmHRrA_zW4cABeKW8BSE7Mn2Am1nqvWpLDQtsTCMYgqhPydOB6EZYy40QOLw0Z3NDTHj2AC238Qly7rMMQ5C2UGPAkoJHWdTRhmtWnnatLDEgXq-M5oSfhSJYO_jI9Jwcw43fY8titkPFQobCaUADvoAyqOa5iDPtRR7XunYP8ho_PSBHmgQQdhvI1xfL9rHerVGsSUgQtb9kgZIUVuwWJD6_tWlEof8BAI2EnTrbyRFc2gwAL27JsBFoh7R5gNcAY-vTK4vD3FTIQsN1JnoYCMf19aEapz3VuIl65qi7ddATjegng&csuir=3)

You can use gdb and jlink's gdb-server from the command line and see if it works. If you cannot make it work via command line, there is no hope of automating it from Cortex-Debug. Remember a few things

1. We never talk to any gdb-server directly after startup. Making an exception here requires a lot of structural code changes
2. To add to above, everything has to be accomplished via GDB commands. We are only a front-end to GDB and do not go behind its back.... doing so will leave gdb in a confused state.
3. Make sure you are using some RTOS with multiple threads in your experiments. We cannot break multi-threading.

Once you have it working, please report back. Open a new issue with relevant info. Do not overload this one

**Comment by haneefdm** [comment]
https://stackoverflow.com/questions/10607021/c-thread-not-stopping-in-gdb-async-mode-using-user-defined-or-python-command-s
