### ISSUE TITLE
cortex debug doesn't launch gdb

### ISSUE THREAD

**Issue by Hermann-Core** [Marus/cortex-debug#946]
### Please make you search through our existing [issues](https://github.com/Marus/cortex-debug/issues?q=type:issue) (both open and closed)
Please visit the correct repo to file an issue. If this is an issue with
* Peripherals/SVD Viewer: [https://github.com/mcu-debug/peripheral-viewer](https://github.com/mcu-debug/peripheral-viewer)
* Memory Viewer: [https://github.com/mcu-debug/memview](https://github.com/mcu-debug/memview)
* RTOS Viewer: [https://github.com/mcu-debug/rtos-views](https://github.com/mcu-debug/rtos-views)
* the debugger itself, continue below

**Describe the bug**
I set cortex debug to debug my ESP32 WROOM 32 board using a modified JLink driver and openocd. I want GDB to attach to my target after flashing the binaries. The flash process worked correctly but after that it seems like GDB tries to flash the board again and dont attach to the target. Is there a way to make cortex debug skipping the flash process and let my parameter override all the commands instead ? so after all the prelaunchCommands GDB launch the debug process ?

**To Reproduce**

1. Start debug session
2. Click on 'Debug with OpenOCD'

**Expected behavior**

I want GDB to launch the debug process directly after executing the prelaunchCommands

**Environment (please complete the following information):**

[comment]: <> Whenever possible, please make sure you are using the latest versions of VSCode and our extension

 - Cortex-Debug Version 1.12.1
 - OS: Windows 11
 - GDB Version: 12.1
 - Compiler Toolchain Version: xtensa-esp-elf 12.1]

**Please include `launch.json`**

*Note: We are unlikely to look at the issue if you do not supply this*
```
{
          "cwd": "${workspaceRoot}",
          "executable": "${workspaceFolder}\\build\\${command:espIdf.getProjectName}.elf",
          "name": "Debug with OpenOCD",
          "request": "launch",
          "type": "cortex-debug",
          "servertype": "openocd",
          "interface": "jtag",
          "configFiles": ["interface/jlink_esp.cfg", "target/esp32.cfg"],
          "searchDir": [],
          "runToEntryPoint": "app_main",
          "showDevDebugOutput": "none",
          "gdbPath": "${command:espIdf.getXtensaGdb}",
          "preLaunchCommands": [
            "set remote hardware-watchpoint-limit 2",
            "mon reset halt",
            "thb app_main",
            "flushregs",
            "mon program_esp build/bootloader/bootloader.bin 0x1000 verify",
            "mon program_esp build/partition_table/partition-table.bin 0x8000 verify",
            "mon program_esp build/GPIO.bin 0x10000 verify",
            "symbol-file build/GPIO.elf",
            "monitor reset halt",
            "flushregs"
          ]
        }
```
![Screenshot 2023-11-01 173532](https://github.com/Marus/cortex-debug/assets/65020150/e53b98e1-1c46-4a70-9865-9edc7292de6a)

![Screenshot 2023-11-01 173614](https://github.com/Marus/cortex-debug/assets/65020150/5b3e9707-2196-4a4d-9dde-f42045e8cfa8)

**Comment by haneefdm** [comment]
Not our bug. You should figure out why your programming is failing. We cannot continue with gdb if the startup process fails.

Also, if you are doing all the work yourself, why not use `overrideLaunchCommands` instead of `preLaunchCommands`. Otherwise, you will be doing stuff and we will be doing stuff and it all gets super confusing. Please read our Wiki

https://github.com/Marus/cortex-debug/wiki/Cortex-Debug-Under-the-hood
https://github.com/Marus/cortex-debug/wiki
https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

Also, do not use `"symbol-file build/GPIO.elf",`. There is a `symbolFiles` property that you can use or else, there will be a mismatch in what we think you are debugging vs what gdb thinks. Global/Static variable, disassembly will not work.
